# coding: utf-8

"""
    Sapliy Fintech API

    Official API for the Sapliy Fintech Ecosystem. Build robust financial applications with our type-safe, high-integrity platform.

    The version of the OpenAPI document: 1.0.0
    Contact: support@sapliy.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sapliyio_fintech.models.automation_flow_execution_step import AutomationFlowExecutionStep
from typing import Optional, Set
from typing_extensions import Self

class AutomationFlowExecution(BaseModel):
    """
    AutomationFlowExecution
    """ # noqa: E501
    id: StrictStr
    flow_id: StrictStr
    flow_version: Optional[StrictInt] = None
    trigger_id: Optional[StrictStr] = None
    status: StrictStr
    current_node_id: Optional[StrictStr] = None
    input: Optional[Dict[str, Any]] = None
    output: Optional[Dict[str, Any]] = None
    steps: Optional[List[AutomationFlowExecutionStep]] = None
    started_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "flow_id", "flow_version", "trigger_id", "status", "current_node_id", "input", "output", "steps", "started_at", "ended_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'running', 'paused', 'completed', 'failed']):
            raise ValueError("must be one of enum values ('pending', 'running', 'paused', 'completed', 'failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutomationFlowExecution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                if _item_steps:
                    _items.append(_item_steps.to_dict())
            _dict['steps'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutomationFlowExecution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "flow_id": obj.get("flow_id"),
            "flow_version": obj.get("flow_version"),
            "trigger_id": obj.get("trigger_id"),
            "status": obj.get("status"),
            "current_node_id": obj.get("current_node_id"),
            "input": obj.get("input"),
            "output": obj.get("output"),
            "steps": [AutomationFlowExecutionStep.from_dict(_item) for _item in obj["steps"]] if obj.get("steps") is not None else None,
            "started_at": obj.get("started_at"),
            "ended_at": obj.get("ended_at")
        })
        return _obj


